# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt1', '0004_joins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joins',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='joins',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='user_id',
            new_name='user',
        ),
    ]
