# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt1', '0005_auto_20161024_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joins',
            new_name='Join',
        ),
    ]
