# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt1', '0006_auto_20161024_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.FileField(default='', upload_to=b''),
        ),
    ]
